export type BuildTotalCatalogEntry = {
  statId: string;
  category: string;
  label: string;
};

/** Generated from finalcategories.csv. */
export const BUILD_TOTAL_CATALOG: readonly BuildTotalCatalogEntry[] = [
  { statId: "increased-assault-rifle-rocket-launcher-and-explosive-physical-damage", category: "Assault Rifles", label: "increased Assault Rifle Physical Damage" },
  { statId: "increased-baton-physical-damage", category: "Batons", label: "increased Baton Physical Damage" },
  { statId: "increased-submachine-gun-baton-weapon-and-salvage-tool-physical-damage", category: "Batons", label: "increased Baton Physical Damage" },
  { statId: "increased-stun-duration-of-stun-batons", category: "Batons", label: "increased Stun Duration of Stun Batons" },
  { statId: "additional-bleeding-wound-with-power-attack", category: "Blade Weapons", label: "Additional Bleeding Wound with Power Attack" },
  { statId: "chance-to-cause-a-bleeding-wound-on-glancing-blows", category: "Blade Weapons", label: "chance to cause a Bleeding Wound on Glancing Blows" },
  { statId: "increased-blade-weapon-physical-damage", category: "Blade Weapons", label: "increased Blade Weapon Physical Damage" },
  { statId: "max-bleeding-wounds-on-targets-using-blade-weapons", category: "Blade Weapons", label: "Max Bleeding Wounds on Targets using Blade Weapons" },
  { statId: "reduced-target-run-speed-with-bleeding-wounds", category: "Blade Weapons", label: "reduced Target run speed with Bleeding Wounds" },
  { statId: "improved-bow-and-crossbow-aim-draw-and-reload-speed", category: "Bow and Crossbow", label: "improved Bow and Crossbow Aim, Draw and Reload Speed" },
  { statId: "increased-bow-and-crossbow-physical-damage", category: "Bow and Crossbow", label: "increased Bow and Crossbow Physical Damage" },
  { statId: "increased-physical-damage-with-spears-bows-crossbows-and-sniper-rifles", category: "Bow and Crossbow", label: "increased Physical Damage with Bows and Crossbows" },
  { statId: "additional-physical-damage-to-stunned-targets-while-using-clubs", category: "Clubs", label: "additional Physical Damage to Stunned Targets while using Clubs" },
  { statId: "increased-chance-to-knock-down-enemies", category: "Clubs", label: "increased chance to knock down enemies" },
  { statId: "increased-club-weapon-physical-damage", category: "Clubs", label: "increased Club Weapon Physical Damage" },
  { statId: "successive-hits-with-clubs-cause-the-last-hit-to-deal-additional-33-physical-damage", category: "Clubs", label: "successive hits with Clubs cause the last hit to deal additional 33% Physical Damage" },
  { statId: "increased-maximum-health", category: "Defense", label: "Maximum Health" },
  { statId: "increased-physical-damage-resistance", category: "Defense", label: "increased Physical Damage Resistance" },
  { statId: "stun-resistance", category: "Defense", label: "Stun Resistance" },
  { statId: "increased-maximum-health", category: "Defense", label: "Maximum Health" },
  { statId: "reduced-heavy-armor-durability-loss", category: "Defense", label: "reduced Heavy Armor durability loss" },
  { statId: "reduced-heavy-armor-movement-and-stamina-penalty", category: "Defense", label: "reduced Heavy Armor movement and stamina penalty" },
  { statId: "reduced-light-armor-durability-loss", category: "Defense", label: "reduced Light Armor durability loss" },
  { statId: "reduced-medium-armor-durability-loss", category: "Defense", label: "reduced Medium Armor durability loss" },
  { statId: "reduced-medium-armor-movement-penalty", category: "Defense", label: "reduced Medium Armor movement penalty" },
  { statId: "reduced-medium-armor-stamina-penalty", category: "Defense", label: "reduced Medium Armor stamina penalty" },
  { statId: "stun-resistance", category: "Defense", label: "Stun Resistance" },
  { statId: "increased-maximum-health", category: "Defense", label: "Maximum Health" },
  { statId: "energy-weapon-damage", category: "Energy Weapons", label: "Energy Weapon Damage" },
  { statId: "improved-rocket-launcher-and-explosive-handling-and-dismemberment-chance", category: "Explosives", label: "improved Rocket Launcher and Explosive Handling and Dismemberment Chance" },
  { statId: "improved-rocket-launcher-reload-speed", category: "Explosives", label: "improved Rocket Launcher Reload Speed" },
  { statId: "increased-assault-rifle-rocket-launcher-and-explosive-physical-damage", category: "Explosives", label: "increased Rocket Launcher and Explosive Physical Damage" },
  { statId: "increased-rocket-launcher-and-explosive-physical-damage", category: "Explosives", label: "increased Rocket Launcher and Explosive Physical Damage" },
  { statId: "chance-to-harvest-an-additional-plant", category: "Farming", label: "Chance to harvest an additional plant" },
  { statId: "farm-plot-crafting-cost", category: "Farming", label: "Farm Plot crafting cost" },
  { statId: "increased-harvesting-area-by-while-using-a-sickle-or-scythe", category: "Farming", label: "Increased harvesting area by while using a Sickle or Scythe" },
  { statId: "increased-chance-to-knockdown-target-using-fist-weapons", category: "Fist Weapons", label: "increased chance to knockdown Target using Fist Weapons" },
  { statId: "increased-chance-to-stun-targets-using-fist-weapons", category: "Fist Weapons", label: "increased chance to Stun Targets using Fist Weapons" },
  { statId: "increased-decapitation-chance-with-punches-to-the-head-using-fist-weapons", category: "Fist Weapons", label: "increased decapitation chance with punches to the head using Fist Weapons" },
  { statId: "increased-fist-weapon-physical-damage", category: "Fist Weapons", label: "increased Fist Weapon Physical Damage" },
  { statId: "increased-amount-of-resources-gathered-from-animals-with-bladed-tools", category: "Hunting and Harvesting", label: "increased amount of resources gathered from animals with Bladed Tools" },
  { statId: "increased-amount-of-resources-gathered-from-boulders-ore-terrain-and-trees-while-using-mining-or-woodcutting-tools", category: "Hunting and Harvesting", label: "increased amount of resources gathered from Boulders, Ore, Terrain and Trees while using Mining or Woodcutting Tools" },
  { statId: "increased-efficiency-of-retrieving-resources-while-harvesting-salvageable-objects-using-salvage-tools", category: "Hunting and Harvesting", label: "increased efficiency of retrieving resources while Harvesting Salvageable Objects using Salvage Tools" },
  { statId: "increased-mining-and-woodcutting-tool-physical-damage", category: "Hunting and Harvesting", label: "increased Mining and Woodcutting Tool Physical Damage" },
  { statId: "increased-mining-tool-physical-damage", category: "Hunting and Harvesting", label: "increased Mining Tool Physical Damage" },
  { statId: "increased-salvage-tool-physical-damage", category: "Hunting and Harvesting", label: "increased Salvage Tool Physical Damage" },
  { statId: "increased-submachine-gun-baton-weapon-and-salvage-tool-physical-damage", category: "Hunting and Harvesting", label: "increased Salvage Tool Physical Damage" },
  { statId: "increased-bobby-pin-and-lockpick-durability", category: "Looting", label: "increased Bobby Pin and Lockpick Durability" },
  { statId: "increased-item-quantity-in-buried-treasure", category: "Looting", label: "increased item quantity in buried treasure" },
  { statId: "increased-loot-stage", category: "Looting", label: "increased Loot Stage" },
  { statId: "increased-looting-speed-when-opening-untouched-containers", category: "Looting", label: "increased looting speed when opening Untouched Containers" },
  { statId: "smaller-buried-treasure-search-area", category: "Looting", label: "smaller Buried Treasure Search Area" },
  { statId: "to-lockpicking", category: "Looting", label: "Lockpicking Level" },
  { statId: "to-loot-stage", category: "Looting", label: "Loot Stage" },
  { statId: "improved-machine-gun-handling-aim-and-reload-speed", category: "Machine Guns", label: "improved Machine Gun Handling, Aim and Reload Speed" },
  { statId: "increased-machine-gun-physical-damage", category: "Machine Guns", label: "increased Machine Gun Physical Damage" },
  { statId: "recover-stamina-on-each-successful-shot-using-machine-guns", category: "Machine Guns", label: "Recover Stamina on each successful shot using Machine Guns" },
  { statId: "decreased-stamina-consumption-while-using-melee-weapons", category: "Melee Weapons", label: "decreased stamina consumption while using Melee Weapons" },
  { statId: "increased-attack-speed-using-clubs-batons-knuckles-knives-and-swords", category: "Melee Weapons", label: "increased Attack Speed using Clubs, Batons, Knuckles, Knives and Swords" },
  { statId: "increased-melee-attack-speed", category: "Melee Weapons", label: "increased Melee Attack Speed" },
  { statId: "increased-melee-physical-damage", category: "Melee Weapons", label: "increased Melee Physical Damage" },
  { statId: "increased-melee-weapon-attack-speed", category: "Melee Weapons", label: "increased Melee Weapon Attack Speed" },
  { statId: "increased-melee-weapon-physical-damage", category: "Melee Weapons", label: "increased Melee Weapon Physical Damage" },
  { statId: "less-stamina-used-by-melee-attacks", category: "Melee Weapons", label: "less Stamina Used by Melee Attacks" },
  { statId: "melee-physical-damage", category: "Melee Weapons", label: "Melee Physical Damage" },
  { statId: "recover-stamina-per-enemy-killed-using-clubs-batons-knuckles-knives-or-swords", category: "Melee Weapons", label: "Recover Stamina per Enemy Killed using Clubs, Batons, Knuckles, Knives or Swords" },
  { statId: "recover-stamina-per-enemy-killed-using-melee-weapons", category: "Melee Weapons", label: "Recover Stamina per Enemy Killed using Melee Weapons" },
  { statId: "carry-weight", category: "Miscellaneous", label: "Carry Weight" },
  { statId: "decreased-damage-taken-from-land-mines", category: "Miscellaneous", label: "decreased damage taken from Land Mines" },
  { statId: "increased-action-skill-experience-gain", category: "Miscellaneous", label: "increased Action Skill Experience gain" },
  { statId: "increased-drone-inventory-carry-weight-limit", category: "Miscellaneous", label: "increased Drone Inventory Carry Weight Limit" },
  { statId: "increased-experience-gain-from-kills", category: "Miscellaneous", label: "increased Experience gain from kills" },
  { statId: "increased-experience-gained-from-electrical-trap-kills", category: "Miscellaneous", label: "increased Experience Gained from Electrical Trap kills" },
  { statId: "increased-gained-exp-from-medical-healing-items", category: "Miscellaneous", label: "increased gained EXP from medical healing items" },
  { statId: "s-increased-delay-timer-when-setting-off-land-mines", category: "Miscellaneous", label: "s increased delay timer when setting off Land Mines" },
  { statId: "skill-experience-gain", category: "Miscellaneous", label: "Skill Experience Gain" },
  { statId: "carry-weight", category: "Miscellaneous", label: "Carry Weight" },
  { statId: "decreased-double-jump-stamina-use", category: "Mobility", label: "decreased Double Jump Stamina use" },
  { statId: "decreased-jumping-stamina-use", category: "Mobility", label: "decreased Jumping Stamina use" },
  { statId: "increased-double-jump-height", category: "Mobility", label: "increased Double Jump Height" },
  { statId: "maximum-stamina", category: "Mobility", label: "Maximum Stamina" },
  { statId: "increased-stamina-regeneration-speed-when-sprinting", category: "Mobility", label: "increased stamina regeneration speed when sprinting" },
  { statId: "m-distance-increased-for-safe-fall", category: "Mobility", label: "m distance increased for safe fall" },
  { statId: "m-increased-safe-fall-distance", category: "Mobility", label: "m increased safe fall distance" },
  { statId: "maximum-stamina", category: "Mobility", label: "Maximum Stamina" },
  { statId: "increased-damage-for-nearby-allies-and-party-members", category: "Party Support", label: "increased Damage for nearby Allies and Party Members" },
  { statId: "increased-health-regeneration-for-nearby-allies-and-party-members", category: "Party Support", label: "increased Health Regeneration for nearby Allies and Party Members" },
  { statId: "increased-loot-for-nearby-allies-and-party-members", category: "Party Support", label: "increased Loot for nearby Allies and Party Members" },
  { statId: "increased-physical-resistance-for-nearby-allies-and-party-members", category: "Party Support", label: "increased Physical Resistance for nearby Allies and Party Members" },
  { statId: "to-all-attributes-for-nearby-allies-and-party-members", category: "Party Support", label: "to all Attributes for nearby Allies and Party Members" },
  { statId: "improved-pistol-fire-rate-and-reload-speed", category: "Pistols", label: "improved Pistol Fire Rate and Reload Speed" },
  { statId: "increased-physical-damage-with-blade-weapons-pistols-and-submachine-guns", category: "Pistols", label: "increased Physical Damage with Blade Weapons, Pistols and Submachine Guns" },
  { statId: "increased-pistol-physical-damage", category: "Pistols", label: "increased Pistol Physical Damage" },
  { statId: "successive-hits-with-pistols-in-a-short-time-cause-the-last-shot-to-deal-additional-33-physical-damage", category: "Pistols", label: "successive hits with Pistols in a short time cause the last shot to deal additional +33% Physical Damage" },
  { statId: "increased-melee-portable-turret-attack-speed", category: "Portable Turrets", label: "increased Melee Portable Turret Attack Speed" },
  { statId: "increased-portable-turret-active-range-by-m", category: "Portable Turrets", label: "Increased Portable Turret active Range by m" },
  { statId: "increased-portable-turret-physical-damage", category: "Portable Turrets", label: "increased Portable Turret Physical Damage" },
  { statId: "increased-ranged-portable-turret-fire-rate", category: "Portable Turrets", label: "increased Ranged Portable Turret Fire Rate" },
  { statId: "increased-ranged-portable-turret-magazine-size-by-rounds", category: "Portable Turrets", label: "Increased Ranged Portable Turret Magazine Size by rounds" },
  { statId: "increased-ranged-portable-turret-reload-speed", category: "Portable Turrets", label: "increased Ranged Portable Turret Reload Speed" },
  { statId: "to-maximum-number-of-allowed-active-portable-turrets", category: "Portable Turrets", label: "to maximum number of allowed active Portable Turrets" },
  { statId: "decreased-stamina-consumption-while-aiming-with-ranged-weapons", category: "Ranged Weapons", label: "decreased stamina consumption while aiming with Ranged Weapons" },
  { statId: "increased-firearm-fire-rate-and-handling", category: "Ranged Weapons", label: "increased Firearm Fire Rate and Handling" },
  { statId: "increased-hip-fire-accuracy", category: "Ranged Weapons", label: "increased Hip Fire Accuracy" },
  { statId: "increased-ranged-physical-damage", category: "Ranged Weapons", label: "increased Ranged Physical Damage" },
  { statId: "increased-ranged-weapon-hip-fire-accuracy", category: "Ranged Weapons", label: "increased Ranged Weapon Hip Fire Accuracy" },
  { statId: "ranged-physical-damage", category: "Ranged Weapons", label: "Ranged Physical Damage" },
  { statId: "reduced-movement-penalty-when-reloading", category: "Ranged Weapons", label: "reduced movement penalty when reloading" },
  { statId: "to-ranged-weapon-target-armor-reduction", category: "Ranged Weapons", label: "to Ranged Weapon Target Armor Reduction" },
  { statId: "attacks-with-shotgun-stun-enemies-for-additional-s-seconds", category: "Shotguns", label: "Attacks with Shotgun stun enemies for additional s seconds" },
  { statId: "attacks-with-shotgun-stun-enemies-for-additional-s-seconds", category: "Shotguns", label: "Attacks with Shotgun stun enemies for additional s seconds" },
  { statId: "attacks-with-shotgun-stun-enemies-for-s-seconds", category: "Shotguns", label: "Attacks with Shotgun stun enemies for s seconds" },
  { statId: "improved-shotgun-fire-rate-and-reload-speed", category: "Shotguns", label: "improved Shotgun Fire Rate and Reload Speed" },
  { statId: "increased-shotgun-physical-damage", category: "Shotguns", label: "increased Shotgun Physical Damage" },
  { statId: "increased-chance-for-sledgehammer-power-attacks-to-knock-down-targets", category: "Sledgehammers", label: "increased chance for Sledgehammer Power Attacks to Knock Down Targets" },
  { statId: "increased-chance-to-knock-down-nearby-targets", category: "Sledgehammers", label: "increased chance to knock down nearby Targets" },
  { statId: "increased-sledgehammer-physical-damage", category: "Sledgehammers", label: "increased Sledgehammer Physical Damage" },
  { statId: "decreased-stamina-consumption-while-aiming-with-sniper-rifles", category: "Sniper Rifles", label: "decreased stamina consumption while aiming with Sniper Rifles" },
  { statId: "improved-sniper-rifle-aim-and-reload-speed", category: "Sniper Rifles", label: "improved Sniper Rifle Aim and Reload Speed" },
  { statId: "increased-physical-damage-with-spears-bows-crossbows-and-sniper-rifles", category: "Sniper Rifles", label: "increased Physical Damage with Sniper Rifles" },
  { statId: "increased-sniper-rifle-physical-damage", category: "Sniper Rifles", label: "increased Sniper Rifle Physical Damage" },
  { statId: "successive-kills-can-trigger-up-to-more-kill-streak-bonus-damage", category: "Sniper Rifles", label: "Successive kills can trigger up to more kill streak bonus damage" },
  { statId: "to-sniper-rifle-target-penetration", category: "Sniper Rifles", label: "to Sniper Rifle Target Penetration." },
  { statId: "increased-physical-damage-with-spears-bows-crossbows-and-sniper-rifles", category: "Spears", label: "increased Physical Damage with Spears" },
  { statId: "increased-polearm-physical-damage", category: "Spears", label: "increased Polearm Physical Damage" },
  { statId: "to-polearm-target-armor-reduction", category: "Spears", label: "to Polearm Target Armor Reduction" },
  { statId: "decreased-action-noise-level", category: "Stealth", label: "decreased action noise level" },
  { statId: "decreased-action-noise-level-and-alerted-target-search-duration", category: "Stealth", label: "decreased action noise level and Alerted Target search duration" },
  { statId: "decreased-alerted-target-search-duration", category: "Stealth", label: "decreased Alerted Target search duration" },
  { statId: "increased-crouch-speed", category: "Stealth", label: "increased Crouch speed" },
  { statId: "increased-crouch-speed-and-stealth-effectiveness-in-low-light", category: "Stealth", label: "increased Crouch Speed and Stealth effectiveness in low light" },
  { statId: "increased-sneak-attack-physical-damage", category: "Stealth", label: "increased Sneak Attack Physical Damage" },
  { statId: "increased-stealth-effectiveness-in-low-light", category: "Stealth", label: "increased stealth effectiveness in low light" },
  { statId: "increased-submachine-gun-baton-weapon-and-salvage-tool-physical-damage", category: "Submachine Guns", label: "increased Submachine Gun Physical Damage" },
  { statId: "increased-submachine-gun-physical-damage", category: "Submachine Guns", label: "increased Submachine Gun Physical Damage" },
  { statId: "decreased-speed-of-food-and-water-loss", category: "Survival and Metabolism", label: "decreased speed of food and water loss" },
  { statId: "increased-critical-injury-healing-speed", category: "Survival and Metabolism", label: "increased Critical Injury healing speed" },
  { statId: "increased-duration-of-consumable-effects", category: "Survival and Metabolism", label: "increased duration of Consumable effects" },
  { statId: "increased-healing-effectiveness-of-medical-healing-items", category: "Survival and Metabolism", label: "increased healing effectiveness of medical healing items" },
  { statId: "increased-heat-and-cold-resistance", category: "Survival and Metabolism", label: "increased Heat and Cold Resistance" },
  { statId: "increased-poison-resistance", category: "Survival and Metabolism", label: "increased Poison Resistance" },
  { statId: "increased-recovery-speed-using-antidotes", category: "Survival and Metabolism", label: "increased recovery speed using antidotes" },
  { statId: "recover-health-every-second-while-not-very-hungry-or-thirsty", category: "Survival and Metabolism", label: "Recover Health every second while not very hungry or thirsty" },
  { statId: "reduced-chance-of-dysentery-when-using-consumables", category: "Survival and Metabolism", label: "reduced chance of Dysentery when using consumables" },
  { statId: "reduced-food-and-water-depletion-when-cold-or-overheated", category: "Survival and Metabolism", label: "reduced food and water depletion when cold or overheated" },
  { statId: "reduced-poison-build-up-speed", category: "Survival and Metabolism", label: "reduced poison build up speed" },
  { statId: "s-increased-underwater-diving-duration", category: "Survival and Metabolism", label: "s increased underwater diving duration" },
  { statId: "to-maximum-food-and-thirst-limit", category: "Survival and Metabolism", label: "to Maximum Food and Thirst Limit" },
  { statId: "to-maximum-food-water", category: "Survival and Metabolism", label: "to Maximum Food/Water" },
  { statId: "additional-mission-reward", category: "Trading and Missions", label: "Additional mission Reward" },
  { statId: "better-prices-when-buying-or-selling-from-traders", category: "Trading and Missions", label: "better prices when Buying or Selling from Traders" },
  { statId: "more-dukes-for-completing-missions", category: "Trading and Missions", label: "more Dukes for completing Missions" },
  { statId: "to-trader-stage", category: "Trading and Missions", label: "to Trader Stage" },
  { statId: "trader-level", category: "Trading and Missions", label: "trader level" },
  { statId: "dismemberment-chance", category: "Weapons", label: "Dismemberment Chance" },
  { statId: "headshot-damage", category: "Weapons", label: "Headshot Damage" },
  { statId: "increased-dismemberment-chance", category: "Weapons", label: "increased Dismemberment Chance" },
];

export type BuildTotalCategoryNode = {
  name: string;
  children?: readonly BuildTotalCategoryNode[];
};

export const BUILD_TOTAL_HIERARCHY: readonly BuildTotalCategoryNode[] = [
  { name: "Player Bonuses", children: [
    { name: "Defense" },
    { name: "Farming" },
    { name: "Hunting and Harvesting" },
    { name: "Looting" },
    { name: "Miscellaneous" },
    { name: "Mobility" },
    { name: "Party Support" },
    { name: "Stealth" },
    { name: "Survival and Metabolism" },
    { name: "Trading and Missions" },
  ] },
  { name: "Weapons", children: [
    { name: "Energy Weapons" },
    { name: "Melee Weapons", children: [
      { name: "Batons" },
      { name: "Blade Weapons" },
      { name: "Clubs" },
      { name: "Fist Weapons" },
      { name: "Sledgehammers" },
      { name: "Spears" },
    ] },
    { name: "Ranged Weapons", children: [
      { name: "Assault Rifles" },
      { name: "Bow and Crossbow" },
      { name: "Explosives" },
      { name: "Machine Guns" },
      { name: "Pistols" },
      { name: "Portable Turrets" },
      { name: "Shotguns" },
      { name: "Sniper Rifles" },
      { name: "Submachine Guns" },
    ] },
  ] },
];
